apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: testglobal-secret
  namespace: sandbox-uat
spec:
  encryptedData:
    TEST_UAT: AgAkJ3qGmxF7aGn0irQgkfAv9lOdq1G4i1wHgvV3sfGVZGCsSf+nTpdM0jI8ELtbZlumAaCOKKCLotsnO6YK7FGB5FZHm4nEj08+F2OGwTxosjLQXbjXaPSY21kW9oAtJpVx+cEF5a9vzHl11nacTCIXNqt6hQF2+3U09DZyWXclavJXa4A0E8ri1iMG75/SPvP6C4AzJz2FMvOuUzx46xxjrhICKSIQlzudvs7Fzer5rsrQ/d6meXWQLZrUAzvZnFjSpYLuB5+f8tHl7ook01sEBG9S8sT4UmLweExowijZoaAyXPqKh4EqUghhs0a30i4fXZQn3fWZCvHt5uvDryN7NHCXuyFCAojywk2kcajn7yg9oACIMqWMCEWukKTdtdqwpUSRJJ3Ve7v1VEZgjhmnKDJAvgO2S+Tq1NA4YB2tXoiuxHYu9KBdzeZ5LHcAFw2FwoCAUxdS7GwuFt+99EYD2vgWcagi6ODsMW7L87EJ2b/3sSFt/G1xAoF0IGZoEsPld8D4dlc1gC9jL3TNcp21VOhl6BDvGde+qYfPuUBgOtuK0tlW60LdQSQF44h4EDPXvCgO7p/QEu/oDBJvvNohtHa1ikxORAuDv0tt/7OGpE2bI+w3jhehNtVNj8uF53uX17VXhZZQ0p6E32vzOwtIAIPbDVJgJ0MyXyu0zl/Bc/xXefd9XNYaEYLpcSiGG+tyfpuKxemF
  template:
    metadata:
      creationTimestamp: null
      name: testglobal-secret
      namespace: sandbox-uat
