apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-chart
  namespace: sandbox-uat
spec:
  encryptedData:
    mariadb-root-password: AgAIrrIi9j3K3DqL/DL0jesut5puaON23UpybeW2w6P03NeoUeuXKEhVm2g8/w//vqd/wq2ATQxFzg6yykIqq693mix4TFymzxvzU44jYwOMRl48msWskpkgPj1SsdW7rzuOeR0TSF9duqNTxOjpuOl8z79giYbxx8FuPrO50JxjXkEUSqSo0jsDb1Hw7yUizA+H54bQLcCbRWalyyLxsBNGkbRQ+WiWtaxysiRqJ9d1MhYJkuig9xpKCBLlMeseSUCglGWshjU19QZ0D/Tqfq+WrNfenCPtEviZ0fXNT1evOIyv41HWWNOlklYtIgTU1W0+SEo3OQnNRar/s6jwxK/U8QuLtOZ58kDOGSpoKjMNYZuDanfqqRnb4ay1CJxIoxORoPTaCseayL9tOA4A7eibrjABNDYKpFGEep39Nl+ZvkulZHtghovDHpohSSePmNPoqJA3EmTW6H1Cx3rYH33gKnmLdn7KLIzxk4zzD6hUBfTL/F4rYaI306ysEUm+1PVHCvJTXQAjImLGvTWNMVRdmioSvv3sG93LYzUE9lJuus8RuKKZwS9/gZwZz/r07TZxteZQ//gp7LcNF3c2lpCrwr0RLTLDFOrezfGdu2iZzKN1m7BnbFEGtRhTUL+by42bD2zdMzcUpUPmqyyTw2bqcZS9EkNXCBzifc9hDJOLXRqBQAKEsJ+uUNEkUw8JoPM1aQxKUi/Z
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-chart
      namespace: sandbox-uat
